name: CI
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '0 0 * * 3' # on every Wednesday
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['lts', '1']   # 'lts' = declared compat floor; '1' = latest stable
        os: [ubuntu-latest]
        arch: [default]
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v6
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  diffopt-integration:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: DiffOpt integration - Julia latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
      - name: Instantiate isolated DiffOpt test environment
        run: >-
          julia --project=test/diffopt -e
          'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run DiffOpt integration tests
        run: julia --color=yes --project=test/diffopt test/diffopt/runtests.jl

  downstream-extension:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Downstream extension package - Julia latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
      - name: Instantiate downstream-package test environment
        run: >-
          julia --project=test/downstream -e
          'using Pkg; Pkg.develop([
          PackageSpec(path=pwd()),
          PackageSpec(path=joinpath(pwd(), "test", "fixtures", "MockOpfExtension"))]);
          Pkg.instantiate()'
      - name: Run downstream-package integration tests
        run: julia --color=yes --project=test/downstream test/downstream/runtests.jl
